# Generated by Django 5.1.4 on 2025-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='describtion',
            field=models.TextField(default=''),
        ),
    ]
